import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { cwd } from 'node:process'

interface RouteRow {
  module: string
  controller: string
  handler: string
  method: string
  path: string
  access: string
  file: string
  line: number
}

const root = cwd()
const rows = listControllerFiles(join(root, 'src', 'modules'))
  .flatMap(parseControllerFile)
  .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))

const outputPath = join(root, 'security', 'api-permission-matrix.md')
mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, renderMarkdown(rows), 'utf8')

console.log(`Generated ${relative(root, outputPath)} with ${rows.length} routes.`)

function parseControllerFile(file: string): RouteRow[] {
  const content = readFileSync(file, 'utf8')
  const lines = content.split(/\r?\n/)
  const controllerLine = lines.findIndex(line => /^\s*@Controller\b/.test(line))
  const classLine = lines.findIndex(line => /^\s*export\s+class\s+/.test(line))
  if (controllerLine < 0 || classLine < 0)
    return []

  const controllerPath = readDecoratorArgument(lines[controllerLine]) ?? ''
  const className = lines[classLine].match(/export\s+class\s+(\w+)/)?.[1] ?? 'UnknownController'
  const classDecorators = readDecoratorBlock(lines, controllerLine, classLine)
  const classAccess = readAccessMetadata(classDecorators)
  const moduleName = relative(join(root, 'src', 'modules'), file).split(/[\\/]/)[0]

  const rows: RouteRow[] = []
  for (let i = classLine + 1; i < lines.length; i += 1) {
    const routeDecorator = readRouteDecorator(lines[i])
    if (!routeDecorator)
      continue

    const methodLine = findNextMethodLine(lines, i + 1)
    if (methodLine < 0)
      continue

    const methodDecorators = readMethodDecoratorBlock(lines, i, methodLine)
    const handler = lines[methodLine].match(/\b(?:async\s+)?(\w+)\s*\(/)?.[1] ?? 'anonymous'
    const access = readAccessMetadata(methodDecorators) ?? classAccess ?? 'MISSING'
    rows.push({
      module: moduleName,
      controller: className,
      handler,
      method: routeDecorator.method,
      path: joinApiPath(controllerPath, routeDecorator.path),
      access,
      file: relative(root, file),
      line: i + 1,
    })
  }
  return rows
}

function readRouteDecorator(line: string): { method: string, path: string } | null {
  const match = line.trim().match(/^@(Get|Post|Put|Patch|Delete|Sse)\b(?:\((.*)\))?/)
  if (!match)
    return null
  return {
    method: match[1].toUpperCase() === 'SSE' ? 'SSE' : match[1].toUpperCase(),
    path: readDecoratorArgument(line) ?? '',
  }
}

function readDecoratorArgument(line: string) {
  const match = line.match(/\(\s*['"`]([^'"`]*)['"`]/)
  return match?.[1]
}

function readDecoratorBlock(lines: string[], start: number, end: number) {
  return lines.slice(Math.max(0, start - 16), end).filter(line => line.trimStart().startsWith('@')).join('\n')
}

function readMethodDecoratorBlock(lines: string[], routeLine: number, methodLine: number) {
  let start = routeLine
  while (start > 0) {
    const previous = lines[start - 1].trim()
    if (previous === '' || previous.startsWith('@')) {
      start -= 1
      continue
    }
    break
  }
  return lines.slice(start, methodLine).filter(line => line.trimStart().startsWith('@')).join('\n')
}

function readAccessMetadata(text: string) {
  const perm = text.match(/@Perm\(([^)]*)\)/)?.[1]?.replace(/\s+/g, ' ').trim()
  if (perm)
    return `Perm(${perm})`
  if (text.includes('@AllowAnon'))
    return 'AllowAnon'
  if (text.includes('@Public'))
    return 'Public'
  return undefined
}

function findNextMethodLine(lines: string[], start: number) {
  for (let i = start; i < Math.min(lines.length, start + 16); i += 1) {
    if (/^\s*(?:async\s+)?\w+\s*\(/.test(lines[i]))
      return i
  }
  return -1
}

function joinApiPath(controllerPath: string, routePath: string) {
  return `/${[controllerPath, routePath].filter(Boolean).join('/')}`.replace(/\/+/g, '/')
}

function renderMarkdown(routeRows: RouteRow[]) {
  const header = [
    '# API Permission Matrix',
    '',
    `Route count: ${routeRows.length}`,
    '',
    'Generated by `pnpm security:matrix` from NestJS controller decorators. Each non-public route must explicitly declare access metadata through `@Perm`, `@AllowAnon`, or `@Public`.',
    '',
    '| Module | Method | Path | Access | Controller.Handler | Source |',
    '|---|---|---|---|---|---|',
  ]

  const body = routeRows.map(row =>
    `| ${escapeCell(row.module)} | ${row.method} | \`${escapeCell(row.path)}\` | \`${escapeCell(row.access)}\` | ${escapeCell(`${row.controller}.${row.handler}`)} | \`${escapeCell(`${row.file}:${row.line}`)}\` |`,
  )

  return [...header, ...body, ''].join('\n')
}

function escapeCell(value: string) {
  return value.replace(/\|/g, '\\|')
}

function listControllerFiles(dir: string): string[] {
  const result: string[] = []
  for (const entry of readdirSync(dir)) {
    const absPath = join(dir, entry)
    const stat = statSync(absPath)
    if (stat.isDirectory()) {
      result.push(...listControllerFiles(absPath))
      continue
    }
    if (entry.endsWith('.controller.ts'))
      result.push(absPath)
  }
  return result
}
